version: "3.9"
networks:
  ForumService:
    driver: bridge
  PersonalAccountService:
    driver: bridge

services:
  forum_service:
    container_name: forum_service
    build:
      context: ./ForumService
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - ForumService
    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: Forum
    ports:
      - "5432"
    networks:
      - ForumService
    volumes:
      - postgres-data:/var/lib/postrgesql/data

  personal_account_service:
    container_name: personal_account_service
    build: 
      context: ./PersonalAccountService
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - PersonalAccountService
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo:latest
    ports:
      - "27017"
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
    networks:
      - PersonalAccountService

volumes:
  postgres-data:
  mongoDb-data: